dist: trusty

language: rust

sudo: required

cache:
    cargo: true

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: beta
    - rust: nightly

addons:
  apt:
    packages:
      - libssl-dev

script:
    - rustc --version
    - cargo clean
    - cargo build
    - cargo test -- --test-threads=1
    - cargo test --release

after_success: |
  [[ $TRAVIS_OS_NAME == "linux" ]] &&
  RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin &&
  cargo tarpaulin --out Xml &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
